// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><script src=\"https://unpkg.com/htmx.org@2.0.4\"></script><title>Index Page</title></head><body><form method=\"post\" action=\"/submit\"><textarea name=\"Decklist\" rows=\"40\" cols=\"60\" placeholder=\"Enter your decklist here\"></textarea><br><br><input type=\"submit\" value=\"Submit\"></form></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

//	templ preview(cards []Card) {
//		<ul>
//			for _, card := range cards {
//				<li>
//					<img src={ card.ImageURIs["normal"] }/>
//					<p>{ card.Name }</p>
//					<p>{ card.Set }</p>
//					<p>{ card.CollectorNumber }</p>
//					if card.Quantity > 1 {
//						<p>{ card.Quantity }</p>
//					}
//				</li>
//			}
//		</ul>
//	}
var _ = templruntime.GeneratedTemplate
